spring.datasource.url=jdbc:postgresql://dpg-d95pmppo3t8c73cdrvb0-a.virginia-postgres.render.com/waterdb_rywt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
