spring.datasource.url=jdbc:postgresql://dpg-d9598uvaqgkc73ert0lg-a.virginia-postgres.render.com:5432/waterdb_tsdd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
